package Formularios;
import Entidades.cobranza;
import SuperClases.SuperCliente;
import SuperClases.SuperCobranza;
import SuperClases.SuperHabitacion;
import SuperClases.SuperProducto;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
public class frmcobranza extends javax.swing.JInternalFrame {

    SuperHabitacion shab = new SuperHabitacion("habitacion.txt");
    DefaultTableModel dtmHabitacion = new DefaultTableModel();
    int filaseleccionadaHabitacion;
    
    SuperCobranza scob = new SuperCobranza("cobranza.txt");
    DefaultTableModel dtmCobranza = new DefaultTableModel();  
    
    SuperProducto spro = new SuperProducto("producto.txt");
    DefaultTableModel dtmProducto = new DefaultTableModel();
    int filaseleccionadaProducto;
    
    SuperCliente scli = new SuperCliente("cliente.txt");
    DefaultTableModel dtmCliente = new DefaultTableModel();
    int filaseleccionadaCliente;
    
    public frmcobranza() {
        initComponents();
        cargarHabitacion();  
        this.setLocation(2,57);
        this.bloquearEstados(false);
        this.btnGuardar.setEnabled(false);        
        this.btnCancelar.setEnabled(false); 
        this.btnbuscarproducto.setEnabled(false);
        this.btnbuscarcliente.setEnabled(false);
        this.btnOperarHabitacion.setEnabled(false);
        this.btnOperarProducto.setEnabled(false);
        this.txtcantidadpro.setEnabled(false);
        this.txtcantidaddias.setEnabled(false);
        this.cbotipohab.setEnabled(false);
        this.btnbuscarhabitacion.setEnabled(false);
        this.btnNuevo.requestFocus();
                              
        cargarCabeceraTableProducto();   
        tamañoCabeceraTableProducto();
        listarTableProducto();
                
        cargarCabeceraTableCliente();   
        tamañoCabeceraTableCliente();                        
        listarTableCliente();  
        
        cargarCabeceraTableHabitacion();   
        tamañoCabeceraTableHabitacion();                        
        listarTableHabitacion();  
        
        cargarCabeceraTableVenta();   
        tamañoCabeceraTableVenta();
        listarTableVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tapVenta = new javax.swing.JTabbedPane();
        tapCobranza = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        btnbuscarcliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid_venta = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        btnbuscarproducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpreciopro = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcantidadpro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttotalpro = new javax.swing.JTextField();
        btnOperarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVenta = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbotipohab = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtpreciohabi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcantidaddias = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttotalhabi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtnumerohabi = new javax.swing.JTextField();
        btnbuscarhabitacion = new javax.swing.JButton();
        btnOperarHabitacion = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttotalapagar = new javax.swing.JTextField();
        txtigv = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        btnOperacionTotal = new javax.swing.JButton();
        tapBuscarCliente = new javax.swing.JPanel();
        panCriterioDeBusqueda9 = new javax.swing.JPanel();
        txtFiltroCliente = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabCliente = new javax.swing.JTable();
        tapBuscarProducto = new javax.swing.JPanel();
        panCriterioDeBusqueda8 = new javax.swing.JPanel();
        txtFiltroProducto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabProducto = new javax.swing.JTable();
        tapHabitacion = new javax.swing.JPanel();
        panCriterioDeBusqueda10 = new javax.swing.JPanel();
        txtFiltroHabitacion = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabHabitacion = new javax.swing.JTable();
        panMantenimiento = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CLIENTE");

        btnbuscarcliente.setText("Buscar");
        btnbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscarcliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarcliente))))
                .addGap(21, 21, 21))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de la Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setText("ID_VENTA");

        txtid_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_ventaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(txtid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel3.setText("Producto :");

        btnbuscarproducto.setText("Buscar");
        btnbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarproductoActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpreciopro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbuscarproducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarproducto)
                    .addComponent(jLabel4)
                    .addComponent(txtpreciopro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Cantidad :");

        jLabel6.setText("Total :");

        btnOperarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOperarProducto.setText("Operar");
        btnOperarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcantidadpro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttotalpro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOperarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcantidadpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txttotalpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOperarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabVenta);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de Hospedaje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("Tipo de habitacion :");

        jLabel8.setText("Precio                    :");

        jLabel12.setText("Cantidad de dias   :");

        jLabel13.setText("Total                     :");

        jLabel14.setText("Nro de habitación :");

        btnbuscarhabitacion.setText("Buscar");
        btnbuscarhabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarhabitacionActionPerformed(evt);
            }
        });

        btnOperarHabitacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOperarHabitacion.setText("Operar");
        btnOperarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperarHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbotipohab, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpreciohabi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumerohabi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcantidaddias, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttotalhabi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOperarHabitacion)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnOperarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbotipohab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarhabitacion))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtpreciohabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtnumerohabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtcantidaddias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txttotalhabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Sub Total :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("IGV   :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Total a Pagar      :");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttotalapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txttotalapagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOperacionTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOperacionTotal.setText("Operacion Total");
        btnOperacionTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacionTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tapCobranzaLayout = new javax.swing.GroupLayout(tapCobranza);
        tapCobranza.setLayout(tapCobranzaLayout);
        tapCobranzaLayout.setHorizontalGroup(
            tapCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapCobranzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tapCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tapCobranzaLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOperacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tapCobranzaLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tapCobranzaLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        tapCobranzaLayout.setVerticalGroup(
            tapCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapCobranzaLayout.createSequentialGroup()
                .addGroup(tapCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tapCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tapCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOperacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tapVenta.addTab("Cobranza", tapCobranza);

        tapBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panCriterioDeBusqueda9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Criterios de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtFiltroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panCriterioDeBusqueda9Layout = new javax.swing.GroupLayout(panCriterioDeBusqueda9);
        panCriterioDeBusqueda9.setLayout(panCriterioDeBusqueda9Layout);
        panCriterioDeBusqueda9Layout.setHorizontalGroup(
            panCriterioDeBusqueda9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCriterioDeBusqueda9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltroCliente)
                .addContainerGap())
        );
        panCriterioDeBusqueda9Layout.setVerticalGroup(
            panCriterioDeBusqueda9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCriterioDeBusqueda9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClienteMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabCliente);

        javax.swing.GroupLayout tapBuscarClienteLayout = new javax.swing.GroupLayout(tapBuscarCliente);
        tapBuscarCliente.setLayout(tapBuscarClienteLayout);
        tapBuscarClienteLayout.setHorizontalGroup(
            tapBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tapBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                    .addComponent(panCriterioDeBusqueda9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tapBuscarClienteLayout.setVerticalGroup(
            tapBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCriterioDeBusqueda9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        tapVenta.addTab("Buscar Cliente", tapBuscarCliente);

        panCriterioDeBusqueda8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Criterios de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtFiltroProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroProductoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panCriterioDeBusqueda8Layout = new javax.swing.GroupLayout(panCriterioDeBusqueda8);
        panCriterioDeBusqueda8.setLayout(panCriterioDeBusqueda8Layout);
        panCriterioDeBusqueda8Layout.setHorizontalGroup(
            panCriterioDeBusqueda8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCriterioDeBusqueda8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltroProducto)
                .addContainerGap())
        );
        panCriterioDeBusqueda8Layout.setVerticalGroup(
            panCriterioDeBusqueda8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCriterioDeBusqueda8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltroProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProductoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabProducto);

        javax.swing.GroupLayout tapBuscarProductoLayout = new javax.swing.GroupLayout(tapBuscarProducto);
        tapBuscarProducto.setLayout(tapBuscarProductoLayout);
        tapBuscarProductoLayout.setHorizontalGroup(
            tapBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapBuscarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tapBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addComponent(panCriterioDeBusqueda8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tapBuscarProductoLayout.setVerticalGroup(
            tapBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapBuscarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCriterioDeBusqueda8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        tapVenta.addTab("Buscar Producto", tapBuscarProducto);

        panCriterioDeBusqueda10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Criterios de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtFiltroHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroHabitacionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panCriterioDeBusqueda10Layout = new javax.swing.GroupLayout(panCriterioDeBusqueda10);
        panCriterioDeBusqueda10.setLayout(panCriterioDeBusqueda10Layout);
        panCriterioDeBusqueda10Layout.setHorizontalGroup(
            panCriterioDeBusqueda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCriterioDeBusqueda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltroHabitacion)
                .addContainerGap())
        );
        panCriterioDeBusqueda10Layout.setVerticalGroup(
            panCriterioDeBusqueda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCriterioDeBusqueda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabHabitacion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabHabitacionMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabHabitacion);

        javax.swing.GroupLayout tapHabitacionLayout = new javax.swing.GroupLayout(tapHabitacion);
        tapHabitacion.setLayout(tapHabitacionLayout);
        tapHabitacionLayout.setHorizontalGroup(
            tapHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tapHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addComponent(panCriterioDeBusqueda10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tapHabitacionLayout.setVerticalGroup(
            tapHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tapHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCriterioDeBusqueda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );

        tapVenta.addTab("Buscar Habitacion", tapHabitacion);

        panMantenimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMantenimientoLayout = new javax.swing.GroupLayout(panMantenimiento);
        panMantenimiento.setLayout(panMantenimientoLayout);
        panMantenimientoLayout.setHorizontalGroup(
            panMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMantenimientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMantenimientoLayout.setVerticalGroup(
            panMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tapVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tapVenta)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroClienteKeyTyped
        filtroCliente("(?i)" + txtFiltroCliente.getText(), tabCliente);
    }//GEN-LAST:event_txtFiltroClienteKeyTyped
    public void filtroCliente(String filtro, JTable jtableBuscar){
        dtmCliente = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dtmCliente);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(filtro));
    }
    
    private void tabClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClienteMouseClicked
        try{
            filaseleccionadaCliente = tabCliente.getSelectedRow();
            if(filaseleccionadaCliente == -1){
                JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                DefaultTableModel modelotablaCliente = (DefaultTableModel) tabCliente.getModel();

                String nombre = tabCliente.getValueAt(filaseleccionadaCliente,1).toString();

                txtcliente.setText(nombre);

                tapVenta.setSelectedIndex(0);
                if(txtproducto.getText().equals("")){
                    btnbuscarproducto.requestFocus();
                }
                
                else{
                    txtcantidadpro.requestFocus();
                }
                JOptionPane.showMessageDialog(this,"¡Cliente encontrado!","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (HeadlessException ex){
            JOptionPane.showMessageDialog(this,"Error" + ex + "\nPor favor inténtelo nuevamente","Mensaje del Sistema",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tabClienteMouseClicked

    private void txtFiltroProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroProductoKeyTyped
        filtroProducto("(?i)" + txtFiltroProducto.getText(), tabProducto);
    }//GEN-LAST:event_txtFiltroProductoKeyTyped

    public void filtroProducto(String filtro, JTable jtableBuscar){
        dtmProducto = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dtmProducto);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(filtro));
    }
    private void tabProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProductoMouseClicked
        try{
            filaseleccionadaProducto = tabProducto.getSelectedRow();
            if(filaseleccionadaProducto == -1){
                JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                DefaultTableModel modelotablaProducto = (DefaultTableModel) tabProducto.getModel();

                
                String nombre = tabProducto.getValueAt(filaseleccionadaProducto,1).toString();
                String precio = tabProducto.getValueAt(filaseleccionadaProducto,3).toString();

               
                txtproducto.setText(nombre);
                txtpreciopro.setText(precio);

                tapVenta.setSelectedIndex(0);
                if(txtcliente.getText().equals("")){
                    btnbuscarcliente.requestFocus();
                }
                else{
                    txtcantidadpro.requestFocus();
                }
                JOptionPane.showMessageDialog(this,"¡Producto encontrado!","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (HeadlessException ex){
            JOptionPane.showMessageDialog(this,"Error" + ex + "\nPor favor inténtelo nuevamente","Mensaje del Sistema",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tabProductoMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        /*this.bloquearEstados(true);
        this.txtIdVenta.setEnabled(false);*/
        this.txtid_venta.setEnabled(false);
        this.txtnumerohabi.setEnabled(false);
        this.txtproducto.setEnabled(false);
        this.txttotalpro.setEnabled(false);
        this.txttotalhabi.setEnabled(false);
        this.txtcliente.setEnabled(false);
        this.limpiar();
        txtid_venta.setText("" + scob.getCorrelativoIdcobranza());
        this.btnNuevo.setEnabled(false);
        this.btnGuardar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.tabVenta.setEnabled(false);
        this.txtpreciohabi.setEnabled(false);
        this.txtpreciopro.setEnabled(false);
        this.txttotalapagar.setEnabled(false);
        this.txtsubtotal.setEnabled(false);
        this.txtigv.setEnabled(false);
        this.txtcantidadpro.setEnabled(true);
        this.txtcantidaddias.setEnabled(true);
        this.cbotipohab.setEnabled(false);
        this.btnbuscarhabitacion.setEnabled(true);
        this.btnOperacionTotal.setEnabled(true);
        this.tabVenta.setEnabled(false);
        tapVenta.setSelectedIndex(0);
        //btnbuscarcliente.requestFocus();

        
        this.btnbuscarproducto.setEnabled(true);
        this.btnbuscarcliente.setEnabled(true);
        this.btnOperarProducto.setEnabled(true);
        this.btnOperarHabitacion.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(ValidarDatos().equals("")){
            if(getIdVenta() == scob.buscarid2(getIdVenta())){
                JOptionPane.showMessageDialog(this,"La venta ya se encuentra registrada","Mensaje de la Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                try{
                    

                    cobranza cob = new cobranza(getCliente(),getIdVenta(),getProducto(),getPrecioPro(),getCantidadPro(),getTotalPro(),getHabitacion(),getNumeroHabitacion(),getPrecioHab(),getCantidadDias(),getTotalHabi(),getSubTotal(),getImpuesto(),getTotalAPagar());
                    scob.adicionar(cob);
                    listarTableVenta();
                    scob.grabar();
                    //this.bloquearEstados(false);
                    this.btnNuevo.setEnabled(true);
                    this.btnGuardar.setEnabled(false);
                    this.btnCancelar.setEnabled(false);
                    this.btnbuscarproducto.setEnabled(false);
                    this.btnbuscarcliente.setEnabled(false);
                    this.btnOperarProducto.setEnabled(false);
                    this.btnOperarHabitacion.setEnabled(false);
                    this.txtcantidaddias.setEnabled(false);
                    this.txtcantidadpro.setEnabled(false);
                    this.cbotipohab.setEnabled(false);
                    this.btnbuscarhabitacion.setEnabled(false);
                    this.btnOperacionTotal.setEnabled(false);
                    tapVenta.setSelectedIndex(0);
                    btnNuevo.requestFocus();
                    this.limpiar();
                    JOptionPane.showMessageDialog(this,"¡Venta agregada con éxito!","Mensaje de la Sistema",JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, e,"Mensaje de la Sistema",JOptionPane.ERROR_MESSAGE); //JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Error" + ValidarDatos(),"Mensaje de la Sistema",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //this.bloquearEstados(false);
        this.btnNuevo.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.tapVenta.setSelectedIndex(0);
        //this.btnNuevo.requestFocus();
        this.limpiar();

        this.btnbuscarproducto.setEnabled(false);
        this.btnbuscarcliente.setEnabled(false);
        this.btnOperarHabitacion.setEnabled(false);
        this.btnOperarProducto.setEnabled(false);
        this.txtcantidaddias.setEnabled(false);
        this.txtcantidadpro.setEnabled(false);
        this.cbotipohab.setEnabled(false);
        this.btnbuscarhabitacion.setEnabled(false);
        this.btnOperacionTotal.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtFiltroHabitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroHabitacionKeyTyped
        // TODO add your handling code here:
        filtroProducto("(?i)" + txtFiltroHabitacion.getText(), tabHabitacion);
    }//GEN-LAST:event_txtFiltroHabitacionKeyTyped

    public void filtroHabitacion(String filtro, JTable jtableBuscar){
        dtmHabitacion = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dtmHabitacion);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(filtro));
    }
    
    private void tabHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHabitacionMouseClicked
        // TODO add your handling code here:
        try{
            filaseleccionadaCliente = tabHabitacion.getSelectedRow();
            if(filaseleccionadaCliente == -1){
                JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                DefaultTableModel modelotablaHabitacion = (DefaultTableModel) tabCliente.getModel();

                String tipo = tabHabitacion.getValueAt(filaseleccionadaCliente,0).toString();
                String precio = tabHabitacion.getValueAt(filaseleccionadaCliente,3).toString();
                String numero = tabHabitacion.getValueAt(filaseleccionadaCliente,2).toString();
                

                cbotipohab.setSelectedItem(tipo);
                txtpreciohabi.setText(precio);
                txtnumerohabi.setText(numero);
                

                tapVenta.setSelectedIndex(0);
                if(txtproducto.getText().equals("")){
                    btnbuscarproducto.requestFocus();
                }
                
                else{
                    txtcantidaddias.requestFocus();
                }
                JOptionPane.showMessageDialog(this,"¡Habitacion encontrada!","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (HeadlessException ex){
            JOptionPane.showMessageDialog(this,"Error" + ex + "\nPor favor inténtelo nuevamente","Mensaje del Sistema",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tabHabitacionMouseClicked

    private void btnbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarclienteActionPerformed
        // TODO add your handling code here:
        tapVenta.setSelectedIndex(1);
        txtFiltroCliente.requestFocus();
        
    }//GEN-LAST:event_btnbuscarclienteActionPerformed

    private void btnbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarproductoActionPerformed
        // TODO add your handling code here:
        tapVenta.setSelectedIndex(2);
        txtFiltroProducto.requestFocus();
    }//GEN-LAST:event_btnbuscarproductoActionPerformed

    private void btnbuscarhabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarhabitacionActionPerformed
        // TODO add your handling code here:
        tapVenta.setSelectedIndex(3);
        txtFiltroHabitacion.requestFocus();
    }//GEN-LAST:event_btnbuscarhabitacionActionPerformed

    private void btnOperarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperarProductoActionPerformed
        // TODO add your handling code here:
        if(txtcantidadpro.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Error" + "\nPor favor ingrese la cantidad de productos de la Compra","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);                      
        }
        else{
            try{
                String valorTotalproducto = Double.toString(getTotalPro());
                txttotalpro.setText(valorTotalproducto);

            }catch(Exception e){               
                JOptionPane.showMessageDialog(this, e,"Mensaje de la Sistema",JOptionPane.ERROR_MESSAGE); //JOptionPane.showMessageDialog(null, e);                
            }
        }
    }//GEN-LAST:event_btnOperarProductoActionPerformed

    private void btnOperarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperarHabitacionActionPerformed
        // TODO add your handling code here:
        if(txtcantidaddias.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Error" + "\nPor favor ingrese la cantidad de dias","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);                      
        }
        else{
            try{
                String valorTotalhabi = Double.toString(getTotalHabi());
                txttotalhabi.setText(valorTotalhabi);
            }catch(Exception e){               
                JOptionPane.showMessageDialog(this, e,"Mensaje de la Sistema",JOptionPane.ERROR_MESSAGE); //JOptionPane.showMessageDialog(null, e);                
            }
        }
    }//GEN-LAST:event_btnOperarHabitacionActionPerformed

    private void btnOperacionTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionTotalActionPerformed
        // TODO add your handling code here:
        if(txttotalpro.getText().equals("") || txttotalhabi.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Error" + "\nPor favor realizar las operaciones respectivas","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);                      
        }
        else if(txttotalapagar.getText().isEmpty() && txttotalhabi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Error" + "\nPor favor realizar las operaciones respectivas......","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try{
                

                String valorSubTotal = Double.toString(getSubTotal());
                txtsubtotal.setText(valorSubTotal);

                String valorImpuesto = Double.toString(getImpuesto());
                txtigv.setText(valorImpuesto); 

                String valorTotalAPagar = Double.toString(getTotalAPagar());
                txttotalapagar.setText(valorTotalAPagar);
            }catch(Exception e){               
                JOptionPane.showMessageDialog(this, e,"Mensaje de la Sistema",JOptionPane.ERROR_MESSAGE); //JOptionPane.showMessageDialog(null, e);                
            }
        }
    }//GEN-LAST:event_btnOperacionTotalActionPerformed

    private void txtid_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_ventaActionPerformed

    public int getIdVenta(){
        return Integer.parseInt(txtid_venta.getText());
    }
    
    
    public String getCliente(){
        return txtcliente.getText();
    }
    
    public String getProducto(){
        return txtproducto.getText();
    }
    
    public String getHabitacion(){
        return cbotipohab.getSelectedItem().toString();
    }
    
    public String getNumeroHabitacion(){
        return txtnumerohabi.getText();
    }
    
    public double getPrecioPro(){
        return Double.parseDouble(txtpreciopro.getText());        
    }
    
    public double getCantidadPro(){
        return Double.parseDouble(txtcantidadpro.getText());
    }
    
    public double getTotalPro(){
        return getCantidadPro() * getPrecioPro();
    }
    
    public double getPrecioHab(){
        return Double.parseDouble(txtpreciohabi.getText());        
    }
    
    public double getCantidadDias(){
        return Double.parseDouble(txtcantidaddias.getText());        
    }
    
    public double getTotalHabi(){
        return getCantidadDias()*getPrecioHab();
    }
    
    
    public double getTotal(){
        return getTotalPro() + getTotalHabi();
    }
    
    public double getSubTotal(){
        return getTotal() * 0.83;
    }
    
    public double getImpuesto(){
        return getTotal() * 0.17; 
    }
    
    public double getTotalAPagar(){
        return getTotal();
    }
    
    public void listarTableVenta(){        
        dtmCobranza.setRowCount(0);
        for(int i=0;i<scob.tamaño();i++){ 
            Object array[] = new Object[14];
            array[0] = scob.obtener(i).getNombrecli(); 
            array[1] = scob.obtener(i).getIdventa(); 
            array[2] = scob.obtener(i).getNombreproducto(); 
            array[3] = scob.obtener(i).getPrecioproducto();
            array[4] = scob.obtener(i).getCantidadproduc();
            array[5] = scob.obtener(i).getTotalpro();
            array[6] = scob.obtener(i).getHabitacion();
            array[7] = scob.obtener(i).getNumerohabitacion();
            array[8] = scob.obtener(i).getPreciohabi();
            array[9] = scob.obtener(i).getCantidaddias();
            array[10] = scob.obtener(i).getTotalhabita();
            array[11] = scob.obtener(i).getSubtotal();
            array[12] = scob.obtener(i).getIgv();
            array[13] = scob.obtener(i).getTotalfinal();
            dtmCobranza.addRow(array); 
        }        
        tabVenta.setModel(dtmCobranza);              
    }
    
    public void cargarCabeceraTableVenta(){
        dtmCobranza.addColumn("NOMBRE CLIENTE"); 
        dtmCobranza.addColumn("ID_VENTA"); 
        dtmCobranza.addColumn("NOMBRE PRODUCTO");
        dtmCobranza.addColumn("PRECIO PRODUCTO");
        dtmCobranza.addColumn("CANTIDAD PRODUCTO");
        dtmCobranza.addColumn("TOTAL PRODUCTO");
        dtmCobranza.addColumn("CATEGORIA DE HABITACION");
        dtmCobranza.addColumn("NUMERO DE HABITACION");        
        dtmCobranza.addColumn("PRECIO HABITACION");
        dtmCobranza.addColumn("CANTIDAD DE DIAS");
        dtmCobranza.addColumn("TOTAL DE HABITACION");
        dtmCobranza.addColumn("SUB TOTAL"); 
        dtmCobranza.addColumn("IGV");
        dtmCobranza.addColumn("TOTAL FINAL");
        tabVenta.setModel(dtmCobranza);
    }       
    
    public void tamañoCabeceraTableVenta(){
        TableColumnModel columnModel = tabVenta.getColumnModel();  
        columnModel.getColumn(0).setPreferredWidth(120);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(2).setPreferredWidth(120);
        columnModel.getColumn(3).setPreferredWidth(120);
        columnModel.getColumn(4).setPreferredWidth(120);
        columnModel.getColumn(5).setPreferredWidth(120);
        columnModel.getColumn(6).setPreferredWidth(120);
        columnModel.getColumn(7).setPreferredWidth(120); 
        columnModel.getColumn(8).setPreferredWidth(120);  
        columnModel.getColumn(9).setPreferredWidth(120);  
        columnModel.getColumn(10).setPreferredWidth(120); 
        columnModel.getColumn(11).setPreferredWidth(120); 
        columnModel.getColumn(12).setPreferredWidth(120); 
        columnModel.getColumn(13).setPreferredWidth(120);
    }
    
    public void listarTableProducto(){        
        dtmProducto.setRowCount(0);
        for(int i=0;i<spro.tamaño();i++){ 
            Object array[] = new Object[11];
            array[0] = spro.obtener(i).getId_pro(); 
            array[1] = spro.obtener(i).getNombre(); 
            array[2] = spro.obtener(i).getCatpro(); 
            array[3] = spro.obtener(i).getPrepro();
            dtmProducto.addRow(array); 
        }        
        tabProducto.setModel(dtmProducto);               
    }
    
    public void cargarCabeceraTableProducto(){
        dtmProducto.addColumn("ID Producto"); 
        dtmProducto.addColumn("Nombre");
        dtmProducto.addColumn("Categoría Producto");
        dtmProducto.addColumn("Precio");    
        tabProducto.setModel(dtmProducto);
    }       
    
    public void tamañoCabeceraTableProducto(){
        TableColumnModel columnModel = tabProducto.getColumnModel();  
        columnModel.getColumn(0).setPreferredWidth(120);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(2).setPreferredWidth(120);
        columnModel.getColumn(3).setPreferredWidth(120);
    }
    
    public void listarTableCliente(){        
        
        dtmCliente.setRowCount(0); //LIMPIA LAS FILAS DEL JTABLE
        for(int i=0;i<scli.tamaño();i++){
            Object vec[]=new Object[6];
            vec[0] = scli.obtener(i).getCodigo();
            vec[1] = scli.obtener(i).getNombre();
            vec[2] = scli.obtener(i).getApellido();
            vec[3] = scli.obtener(i).getDni();
            vec[4] = scli.obtener(i).getEdad();
            vec[5] = scli.obtener(i).getSexo();
            
            //AGREGAR AL JTABLE
            dtmCliente.addRow(vec);
        }
        tabCliente.setModel(dtmCliente);
    }
    
    public void cargarCabeceraTableCliente(){
        dtmCliente.addColumn("Codigo");
        dtmCliente.addColumn("Nombre");
        dtmCliente.addColumn("Apellido");
        dtmCliente.addColumn("DNI");
        dtmCliente.addColumn("Edad");
        dtmCliente.addColumn("Sexo");            
        tabCliente.setModel(dtmCliente);
    }       
    
    public void tamañoCabeceraTableCliente(){
        TableColumnModel columnModel = tabCliente.getColumnModel();  
        columnModel.getColumn(0).setPreferredWidth(120);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(2).setPreferredWidth(120);
        columnModel.getColumn(3).setPreferredWidth(120);
        columnModel.getColumn(4).setPreferredWidth(120);
        columnModel.getColumn(5).setPreferredWidth(120);    
    }
    
    public void listarTableHabitacion(){        
        
       dtmHabitacion.setRowCount(0);
        for(int i=0;i<shab.tamaño();i++){ 
            Object array[] = new Object[4];
            array[0] = shab.obtener(i).getCategoria(); 
            array[1] = shab.obtener(i).getPiso(); 
            array[2] = shab.obtener(i).getNumero(); 
            array[3] = shab.obtener(i).getPrecio();
            dtmHabitacion.addRow(array); 
        }        
        tabHabitacion.setModel(dtmHabitacion);
    }
    
    public void cargarCabeceraTableHabitacion(){
        dtmHabitacion.addColumn("Categoria Habitacion"); 
        dtmHabitacion.addColumn("Piso");
        dtmHabitacion.addColumn("Numero");
        dtmHabitacion.addColumn("Precio");    
        tabHabitacion.setModel(dtmHabitacion);
    }       
    
    public void tamañoCabeceraTableHabitacion(){
        TableColumnModel columnModel =tabHabitacion.getColumnModel();  
        columnModel.getColumn(0).setPreferredWidth(120);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(2).setPreferredWidth(120);
        columnModel.getColumn(3).setPreferredWidth(120);
    }
    
        
    public void bloquearEstados(boolean estado){        
        this.txtnumerohabi.setEnabled(false);
        this.txtproducto.setEnabled(false);
        this.txttotalpro.setEnabled(false);
        this.txttotalhabi.setEnabled(false);
        this.txtcliente.setEnabled(false);this.limpiar();
        this.btnNuevo.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnCancelar.setEnabled(true);
        this.tabVenta.setEnabled(false);
        //this.txtcantidadpro.setEnabled(false);
        this.txtid_venta.setEnabled(false);
        //this.txtcantidaddias.setEnabled(false);
        this.txtpreciohabi.setEnabled(false);
        this.txtpreciopro.setEnabled(false);
        this.txttotalapagar.setEnabled(false);
        this.txtsubtotal.setEnabled(false);
        this.txtigv.setEnabled(false);
        this.tabVenta.setEnabled(false);
        tapVenta.setSelectedIndex(0);
        //this.cbotipohab.setEnabled(false);
        this.btnbuscarproducto.setEnabled(false);
        //this.btnbuscarhabitacion.setEnabled(false);
        this.btnOperacionTotal.setEnabled(false);
        this.btnbuscarcliente.setEnabled(false);
        this.btnOperarProducto.setEnabled(false);
        this.btnOperarHabitacion.setEnabled(false);                      
    }
       
    public void limpiar(){  
        this.txtcliente.setText("");
        this.txtid_venta.setText("");
        this.txtproducto.setText("");
        this.txtpreciopro.setText("");
        this.txtcantidadpro.setText("");
        this.txttotalpro.setText("");
        this.cbotipohab.setSelectedIndex(0);
//        this.txtFecha.setText("");                      
        this.txtpreciohabi.setText("");
        this.txtnumerohabi.setText("");
        this.txtcantidaddias.setText("");
        this.txttotalhabi.setText("");
        this.txtsubtotal.setText("");
        this.txtigv.setText("");
        this.txttotalapagar.setText("");
    }   
    
    public void cargarHabitacion(){
        for(int i=0;i<shab.tamaño();i++){             
            cbotipohab.addItem(shab.obtener(i).getCategoria().toString()); 
        }  
    }
    
    public String ValidarDatos(){
        String mensajeValidarDatos = "";
        if(txtcliente.getText().equals("")){
            mensajeValidarDatos += "\nPor favor ingrese los datos del Cliente";
            txtcliente.requestFocus();
        } 
        if(txtproducto.getText().equals("")){
            mensajeValidarDatos += "\nPor favor ingrese los datos del Producto";
            txtproducto.requestFocus();
        } 
        if(txtcantidadpro.getText().equals("")){
            mensajeValidarDatos += "\nPor favor ingrese los datos del Producto";
            txtcantidadpro.requestFocus();
        }                   
        if(txttotalpro.getText().equals("")){
            mensajeValidarDatos += "\nPor favor Opere el producto";
            txttotalpro.requestFocus();
        }                          
        if(txtcantidaddias.getText().equals("")){
            mensajeValidarDatos += "\nPor favor ingrese la cantidad de dias de la habitacion";
            txtcantidaddias.requestFocus();
        }
        if(txttotalhabi.getText().equals("")){
            mensajeValidarDatos += "\nPor favor opere los datos de la habitacion";
        }
        return mensajeValidarDatos;              
    }  
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOperacionTotal;
    private javax.swing.JButton btnOperarHabitacion;
    private javax.swing.JButton btnOperarProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnbuscarcliente;
    private javax.swing.JButton btnbuscarhabitacion;
    private javax.swing.JButton btnbuscarproducto;
    private javax.swing.JComboBox<String> cbotipohab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panCriterioDeBusqueda10;
    private javax.swing.JPanel panCriterioDeBusqueda8;
    private javax.swing.JPanel panCriterioDeBusqueda9;
    private javax.swing.JPanel panMantenimiento;
    private javax.swing.JTable tabCliente;
    private javax.swing.JTable tabHabitacion;
    private javax.swing.JTable tabProducto;
    private javax.swing.JTable tabVenta;
    private javax.swing.JPanel tapBuscarCliente;
    private javax.swing.JPanel tapBuscarProducto;
    private javax.swing.JPanel tapCobranza;
    private javax.swing.JPanel tapHabitacion;
    private javax.swing.JTabbedPane tapVenta;
    private javax.swing.JTextField txtFiltroCliente;
    private javax.swing.JTextField txtFiltroHabitacion;
    private javax.swing.JTextField txtFiltroProducto;
    private javax.swing.JTextField txtcantidaddias;
    private javax.swing.JTextField txtcantidadpro;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtid_venta;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtnumerohabi;
    private javax.swing.JTextField txtpreciohabi;
    private javax.swing.JTextField txtpreciopro;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotalapagar;
    private javax.swing.JTextField txttotalhabi;
    private javax.swing.JTextField txttotalpro;
    // End of variables declaration//GEN-END:variables
}
