package Formularios;
import Entidades.Producto;
import SuperClases.SuperCategoriaProducto;
import SuperClases.SuperProducto;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
public class frmProducto extends javax.swing.JInternalFrame {
    SuperCategoriaProducto scp = new SuperCategoriaProducto("categoria producto.txt");
    SuperProducto sp = new SuperProducto("producto.txt");
    DefaultTableModel dtmProducto = new DefaultTableModel();
    int filaseleccionada;    
    public frmProducto() {
        initComponents();
        this.setLocation(2,57);
        //this.setLocation(5,107); 
        //this.setSize(820,387);
        cargarCabeceraTable();   
        tamañoCabeceraTable();
        ordenTabulacion();
        listarTable();       
        cargarCboCategoria();
        this.btnGuardar.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.txtidproduc.setEnabled(false);
        this.txtnompro.setEnabled(false);
        this.cbocatpro.setEnabled(false);
        this.txtprepro.setEnabled(false);
        this.txtbuscar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tapProducto = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtproducto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidproduc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnompro = new javax.swing.JTextField();
        cbocatpro = new javax.swing.JComboBox<>();
        txtprepro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        tapProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Criterios de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbuscar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtproductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtproducto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tapProducto.addTab("Buscar", jPanel1);

        jLabel1.setText("ID_Producto   :");

        jLabel2.setText("Nombre           :");

        jLabel3.setText("Precio              :");

        jLabel4.setText("Categoria        :");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("PRODUCTO :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidproduc, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtprepro)
                                    .addComponent(cbocatpro, javax.swing.GroupLayout.Alignment.TRAILING, 0, 133, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnompro))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)))
                .addGap(191, 191, 191))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidproduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnompro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbocatpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtprepro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        tapProducto.addTab("Nuevo/Modificar", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Botones"));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tapProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tapProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.limpiar(); 
        this.btnNuevo.setEnabled(false);
        this.btnGuardar.setEnabled(true);        
        this.btnModificar.setEnabled(false);
        this.btnCancelar.setEnabled(true);
        tapProducto.setSelectedIndex(1);
        this.txtidproduc.setEnabled(true);
        this.txtnompro.setEnabled(true);
        this.cbocatpro.setEnabled(true);
        this.txtprepro.setEnabled(true);
        txtidproduc.requestFocus(); 
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(ValidarDatos().equals("")){
            if(getId_Producto().equalsIgnoreCase(sp.buscarid2(getId_Producto()))){
                JOptionPane.showMessageDialog(this,"El producto ya se encuentra registrado","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else if(getNombre().equalsIgnoreCase(sp.buscarnom2(getNombre()))){
                JOptionPane.showMessageDialog(this,"El producto ya se encuentra registrado","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }            
            else{
                try{
                    Producto p = new Producto(getId_Producto(),getNombre(),getCategoria(),getPrecio());                 
                    sp.adicionar(p); 
                    listarTable();
                    sp.grabar();             
                    //this.bloquearEstados(false);            
                    this.btnNuevo.setEnabled(true);
                    this.btnGuardar.setEnabled(false);
                    this.btnModificar.setEnabled(false);
                    this.btnCancelar.setEnabled(false);                  
                    this.requestFocus();
                    this.limpiar();               
                    JOptionPane.showMessageDialog(this,"¡Producto agregado con éxito!","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception e){               
                    JOptionPane.showMessageDialog(this, e,"Mensaje del Sistema",JOptionPane.ERROR_MESSAGE); //JOptionPane.showMessageDialog(null, e);                
                }
            }    
        } 
        else{
            JOptionPane.showMessageDialog(this,"Error" + ValidarDatos(),"Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(ValidarDatos().equals("")){
            if(getNombre().equalsIgnoreCase(sp.buscarnommod(getNombre(), getId_Producto()))){
                JOptionPane.showMessageDialog(this,"El producto ya se encuentra registrado","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            this.txtidproduc.setEnabled(false);
            this.txtnompro.setEnabled(false);
            this.cbocatpro.setEnabled(false);
            this.txtprepro.setEnabled(false);
            this.btnNuevo.setEnabled(true);
            this.btnGuardar.setEnabled(false); 
            this.btnModificar.setEnabled(false);
            this.btnCancelar.setEnabled(false);
            }
            else{
                try{
                    Producto p = sp.buscarid(getId_Producto());                         
//                    obj.setIdEmp(getIdProducto()); //Al modificar no cambiara el ID Producto
                    p.setId_pro(getId_Producto()); 
                    p.setNombre(getNombre());
                    p.setCatpro(getCategoria());
                    p.setPrepro(getPrecio()); //Al modificar si cambiara la utilidad, dependiendo del precio costo y del precio venta
                    listarTable();
                    sp.grabar();                    
                    //this.bloquearEstados(false);
                    this.btnNuevo.setEnabled(true);
                    this.btnGuardar.setEnabled(false); 
                    this.btnModificar.setEnabled(false);
                    this.btnCancelar.setEnabled(false);
                    this.requestFocus();
                    this.limpiar();
                    JOptionPane.showMessageDialog(this,"¡Registro actualizado con éxito!","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);                                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, e,"Mensaje del Sistema",JOptionPane.ERROR_MESSAGE); //JOptionPane.showMessageDialog(null, e);  
                }
            }    
        }
        else{
            JOptionPane.showMessageDialog(this,"Error" + ValidarDatos(),"Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);                       
        } 

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        //this.bloquearEstados(false);
        this.btnNuevo.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.txtidproduc.setEnabled(false);
        this.txtnompro.setEnabled(false);
        this.cbocatpro.setEnabled(false);
        this.txtprepro.setEnabled(false);
        this.requestFocus();
        this.limpiar(); 
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        // TODO add your handling code here:
        filtro("(?i)" + txtbuscar.getText(), jtproducto);
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void jtproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtproductoMouseClicked
        // TODO add your handling code here:
        try{
            filaseleccionada = jtproducto.getSelectedRow();
            if(filaseleccionada == -1){
                JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                DefaultTableModel modelotabla = (DefaultTableModel) jtproducto.getModel();

                String id = jtproducto.getValueAt(filaseleccionada,0).toString();
                String nombre = jtproducto.getValueAt(filaseleccionada,1).toString();
                String categoria = jtproducto.getValueAt(filaseleccionada,2).toString();
                String precio = jtproducto.getValueAt(filaseleccionada,3).toString(); //No se obtendra el valor de utilidad            

                txtidproduc.setText(id);
                txtnompro.setText(nombre);
                cbocatpro.setSelectedItem(categoria);
                
                txtprepro.setText(precio);            

                //this.bloquearEstados(true);
                this.btnNuevo.setEnabled(false);
                this.btnGuardar.setEnabled(false);
                this.btnModificar.setEnabled(true);
                this.btnCancelar.setEnabled(true);
                this.txtidproduc.setEnabled(true);
                this.txtnompro.setEnabled(true);
                this.cbocatpro.setEnabled(true);
                this.txtprepro.setEnabled(true);
                tapProducto.setSelectedIndex(1);
                txtidproduc.requestFocus();
                JOptionPane.showMessageDialog(this,"¡Producto encontrado!","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (HeadlessException ex){
            JOptionPane.showMessageDialog(this,"Error" + ex + "\nPor favor inténtelo nuevamente","Mensaje del Sistema",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jtproductoMouseClicked
    public void filtro(String filtro, JTable jtableBuscar){
        dtmProducto = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dtmProducto);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(filtro));
    }
    
    public String getId_Producto(){
        return txtidproduc.getText();        
    }
    
    public String getNombre(){
        return txtnompro.getText();
    } 
    
    public String getCategoria(){
        return cbocatpro.getSelectedItem().toString();
    }
    
    public double getPrecio(){
        return Double.parseDouble(txtprepro.getText());
    }
    
    public void listarTable(){        
        dtmProducto.setRowCount(0);
        for(int i=0;i<sp.tamaño();i++){ 
            Object array[] = new Object[11];
            array[0] = sp.obtener(i).getId_pro(); 
            array[1] = sp.obtener(i).getNombre(); 
            array[2] = sp.obtener(i).getCatpro(); 
            array[3] = sp.obtener(i).getPrepro();
            dtmProducto.addRow(array); 
        }        
        jtproducto.setModel(dtmProducto);               
    }
    
    public void cargarCabeceraTable(){
        dtmProducto.addColumn("ID Producto"); 
        dtmProducto.addColumn("Nombre");
        dtmProducto.addColumn("Categoría Producto");
        dtmProducto.addColumn("Precio");    
        jtproducto.setModel(dtmProducto);
    }       
    
    public void tamañoCabeceraTable(){
        TableColumnModel columnModel = jtproducto.getColumnModel();  
        columnModel.getColumn(0).setPreferredWidth(120);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(2).setPreferredWidth(120);
        columnModel.getColumn(3).setPreferredWidth(120);
    }
    
    public void ordenTabulacion(){  
        txtidproduc.setNextFocusableComponent(txtnompro);
        txtnompro.setNextFocusableComponent(cbocatpro); 
        cbocatpro.setNextFocusableComponent(txtprepro);
        txtprepro.setNextFocusableComponent(btnNuevo);
//        btnGenerar.setNextFocusableComponent(btnImprimir);
//        btnImprimir.setNextFocusableComponent(btnNuevo);
        btnNuevo.setNextFocusableComponent(btnGuardar);
        btnGuardar.setNextFocusableComponent(btnModificar);
        btnModificar.setNextFocusableComponent(btnCancelar);
        btnCancelar.setNextFocusableComponent(btnSalir);
        btnSalir.setNextFocusableComponent(txtidproduc);        
    }
    
    /*public void bloquearEstados(boolean estado){
        this.txtIdProducto.setEnabled(estado);
        this.txtCodigoDeBarras.setEnabled(estado);
        this.txtNombre.setEnabled(estado);
        this.txtDescripcion.setEnabled(estado);
        this.cboCategoria.setEnabled(estado);
        this.ACTIVO.setEnabled(estado);
        this.INACTIVO.setEnabled(estado);
        this.txtStock.setEnabled(estado);
        this.txtStockMinimo.setEnabled(estado);
        this.txtPrecioCosto.setEnabled(estado);             
        this.txtPrecioVenta.setEnabled(estado);
        this.txtUtilidad.setEnabled(estado); 
    }*/
       
    public void limpiar(){  
        this.txtidproduc.setText("");
        this.txtnompro.setText("");
        this.cbocatpro.setSelectedIndex(0);
        this.txtprepro.setText("");
    }   
    
    public void cargarCboCategoria(){
        for(int i=0;i<scp.tamaño();i++){             
            cbocatpro.addItem(scp.obtener(i).getCategoriapro().toString()); 
        }
    }
    
    
    public String ValidarDatos(){
        String mensajeValidarDatos = "";        
        if(txtidproduc.getText().equals("")){
            mensajeValidarDatos += "\nPor favor ingrese el id del Producto";
            txtidproduc.requestFocus();
        }
        if(txtnompro.getText().equals("")){
            mensajeValidarDatos += "\nPor favor ingrese el nombre del Producto";
            txtnompro.requestFocus();
        }
        if(txtprepro.getText().equals("")){
            mensajeValidarDatos += "\nPor favor ingrese el precio del Producto";
            txtprepro.requestFocus();
        }
//        if(txtUtilidad.getText().equals("")){
//            mensajeValidarDatos += "\nPor favor ingrese la ulilidad del Producto";
//            txtUtilidad.requestFocus();
//        }         
        return mensajeValidarDatos;               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbocatpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtproducto;
    private javax.swing.JTabbedPane tapProducto;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtidproduc;
    private javax.swing.JTextField txtnompro;
    private javax.swing.JTextField txtprepro;
    // End of variables declaration//GEN-END:variables
}
