package Formularios;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.awt.Image;
import java.net.URI;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Vistas.mtnHabitacion;
public class frmprincical extends javax.swing.JFrame {

    public frmprincical() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("                                                                                                                            " + "RESERVACIONES HOTEL MARRIOT S.A.C  //  EMPRESA");
        this.setVisible(true);
        this.setContentPane(this.jPrincipal);
        ImageIcon imagen = new ImageIcon("src/Imagenes/Principal.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblPrincipal.getWidth(), lblPrincipal.getHeight(), Image.SCALE_DEFAULT));
        lblPrincipal.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnHabitaciones = new javax.swing.JButton();
        btnCategoriaProducto = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnCategoriaHabitacion = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnCobranzas = new javax.swing.JButton();
        lblPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        micalculadora = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mipaginaweb = new javax.swing.JMenuItem();
        jmenuexit = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/habitacion_opt.png"))); // NOI18N
        btnHabitaciones.setText("Habitaciones");
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });

        btnCategoriaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Prducto.png"))); // NOI18N
        btnCategoriaProducto.setText("Categoria de Producto");
        btnCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaProductoActionPerformed(evt);
            }
        });

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente_opt.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnCategoriaHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/categoriahabitaqcion_opt.png"))); // NOI18N
        btnCategoriaHabitacion.setText("Categoria \nde \nHabitacion");
        btnCategoriaHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaHabitacionActionPerformed(evt);
            }
        });

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto_opt.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnCobranzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cobranza_opt.png"))); // NOI18N
        btnCobranzas.setText("Cobranza");
        btnCobranzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobranzasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnHabitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoriaProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoriaHabitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCobranzas))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCategoriaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCobranzas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPrincipal.add(jPanel1);
        jPanel1.setBounds(0, 0, 990, 56);
        jPrincipal.add(lblPrincipal);
        lblPrincipal.setBounds(0, 0, 1670, 820);

        getContentPane().add(jPrincipal);
        jPrincipal.setBounds(0, 0, 840, 460);

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        jMenuItem9.setText("Salir");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Herramientas");

        micalculadora.setText("Calculadora");
        micalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micalculadoraActionPerformed(evt);
            }
        });
        jMenu6.add(micalculadora);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("Ayuda");

        mipaginaweb.setText("Pagina web");
        mipaginaweb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mipaginawebMouseClicked(evt);
            }
        });
        mipaginaweb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mipaginawebActionPerformed(evt);
            }
        });
        jMenu4.add(mipaginaweb);

        jMenuBar1.add(jMenu4);

        jmenuexit.setText("Exit");
        jmenuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuexitActionPerformed(evt);
            }
        });

        jMenuItem11.setText("Salir");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jmenuexit.add(jMenuItem11);

        jMenuBar1.add(jmenuexit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code her
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jmenuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuexitActionPerformed
        // TODO add your handling code here:
        /*dispose();
        frmlogin lo = new frmlogin();
        lo.setVisible(true);*/
    }//GEN-LAST:event_jmenuexitActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        dispose();
        frmlogin lo = new frmlogin();
        lo.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void mipaginawebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mipaginawebActionPerformed
        // TODO add your handling code here:
        AbrirInternet();
    }//GEN-LAST:event_mipaginawebActionPerformed

    private void mipaginawebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mipaginawebMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mipaginawebMouseClicked

    private void micalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micalculadoraActionPerformed
        // TODO add your handling code here:
        Calculadora();
    }//GEN-LAST:event_micalculadoraActionPerformed

    private void btnCategoriaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaHabitacionActionPerformed
        frmCategoriaHabitacion ch = new frmCategoriaHabitacion();
        ch.setVisible(true);
        this.lblPrincipal.add(ch);
    }//GEN-LAST:event_btnCategoriaHabitacionActionPerformed

    private void btnCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaProductoActionPerformed
        frmCategoriaProducto cp = new frmCategoriaProducto();
        cp.setVisible(true);
        this.lblPrincipal.add(cp);
    }//GEN-LAST:event_btnCategoriaProductoActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        frmCliente c = new frmCliente();
        c.setVisible(true);
        this.lblPrincipal.add(c);
         
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
        
        mtnHabitacion h = new mtnHabitacion();
        h.setVisible(true);
        this.lblPrincipal.add(h);
         
     
    }//GEN-LAST:event_btnHabitacionesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        frmProducto p = new frmProducto();
        p.setVisible(true);
        this.lblPrincipal.add(p);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCobranzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobranzasActionPerformed
        frmcobranza c = new frmcobranza();
        c.setVisible(true);
        this.lblPrincipal.add(c);
    }//GEN-LAST:event_btnCobranzasActionPerformed
    public void AbrirInternet(){
        try{
            Desktop.getDesktop().browse(URI.create("https://www.espanol.marriott.com/default.mi"));
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }
    
    public void Calculadora(){
          try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (Exception e){
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprincical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprincical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprincical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprincical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprincical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoriaHabitacion;
    private javax.swing.JButton btnCategoriaProducto;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCobranzas;
    private javax.swing.JButton btnHabitaciones;
    private javax.swing.JButton btnProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jPrincipal;
    private javax.swing.JMenu jmenuexit;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JMenuItem micalculadora;
    private javax.swing.JMenuItem mipaginaweb;
    // End of variables declaration//GEN-END:variables
}
